version: '3.9'

networks:
  network_ddg:
    external: true

services:
  node-app:
    build:
      context: .
      dockerfile: ./docker/server/Dockerfile
    container_name: '${APP_NAME}'
    ports:
      - '4200:4200'
    working_dir: /app
    volumes:
      - ./codebase:/app
    networks:
      - network_ddg